###### Redis Store Props #######
session:
    redis:
      name: session-store:local
      mode: standalone
      standalone:
        host: localhost
        port: 6379
        usePooling: false
        enableJmx: false
      connection:
        timeout: 1000
        maxTotal: 200
        minIdle: 50
        maxIdle: 100

######### MongoDB properties
app:
  mongo:
    sources:
      payment:
        nodes: 10.80.0.73,10.80.0.68:27017
        username: # None
        password: # None
        database: payments

##### mysql database props #####
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: root
    password: root
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/payments
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 5000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 10
      maximumPoolSize: 100

  #### JPA props ######
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: UTC

#### logging props ####
logging:
  path: /tmp

####### payment props #######
payment:
  merchant:
    ####### payu props #########
    payu:
      api:
        info: https://info.payu.in/merchant/postservice.php?form=2
      internal:
        web:
          url: https://wcfpay-new.wynk.in/wcf/payu
        callback:
          successUrl: http://localhost:8081/payment/callback/{sid}
          failureUrl: http://localhost:8081/payment/callback/{sid}
      command:
        verifyVpa: validateVPA
        checkIsDomestic: check_isDomestic