###### Redis Store Props #######
session:
  redis:
    name: session-store:prod
    mode: cluster
    useSsl: false
    usePooling: true
    password: ##
    enableJmx: true
    jmxPrefix: session-store:prod
    cluster:
      nodes: 127.0.0.1,127.0.0.1

app:
  mongo:
    sources:
      se:
        nodes: 10.40.12.133:27017,10.40.12.139:27017,10.40.12.140:27017
        username: # None
        password: # None
        database: sedb