######  Properties #########
paytm:
  native:
    clientId: merchant-wynk-staging
    merchantKey: 6UePBAcq7LTfdGJI
    merchantId: WYNKLI36809118294255
    secret: 653fe766-5864-4e16-a288-68ebcccffbd0
    accounts:
      baseUrl: https://accounts-uat.paytm.com
    services:
      baseUrl: https://securegw-stage.paytm.in/paymentservices
    wcf:
      addMoneyUrl: http://wcfpay-dev.wynk.in/paytm-native/add-money
      callbackUrl: http://localhost:8181/wynk/v2/s2s/subscription/callback?sid=
  requesting:
    website: WCF

apb:
  txn:
    inquiry:
      url: https://apptest.airtelbank.com/ecom/v2/inquiry
  callback:
    url: http://payment-staging.wynk.in/wynk/wynk/v1/paymentcallback/apb
  merchant:
    id: 180704
  salt: d41d8cd98f00a
  init:
    payment:
      url: https://apptest.airtelbank.com/ecom/v2/initiatePayment


###### Redis Store Props #######
session:
  redis:
    name: session-store:local
    mode: standalone
    standalone:
      host: 10.80.1.111
      port: 6379
      usePooling: false
      enableJmx: false
    connection:
      timeout: 1000
      maxTotal: 200
      minIdle: 50
      maxIdle: 100

######### MongoDB properties
app:
  mongo:
    sources:
      payment:
        nodes: 10.80.0.73,10.80.0.68:27017
        username: # None
        password: # None
        database: payments

##### mysql database props #####
spring:
  datasource:
    url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
    username: admin
    password: o7QZ?!n=eu
    hikari:
      jdbc-url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
      username: admin
      password: o7QZ?!n=eu
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 5000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 10
      maximumPoolSize: 100

  #### JPA props ######
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: false
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: UTC

####### payment props #######
payment:
  encKey: BSB$PORTAL@2014#
  success:
    page: https://www.google.com/
  failure:
    page: https://www.yahoo.com
  recurring:
    offset:
      day: 0
      hour: 1
  ###### lib-queue props ######
  pooling:
    queue:
      reconciliation:
        enabled: true
        name: wcf-staging-payment-reconciliation
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      renewal:
        enabled: false
        name: wcf-staging-payment-renewal
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      charging:
        enabled: false
        name: wcf-staging-payment-charging.fifo
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      subscription:
        enabled: false
        name: wcf-staging-subscription
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
  ###### webview status props #######
  status:
    web:
      url: http://localhost:4200/status
  merchant:
    ####### payu props #########
    payu:
      key: aU2Uoi
      salt: 6vbnfVtw
      api:
        info: https://info.payu.in/merchant/postservice.php?form=2
      internal:
        web:
          url: https://wcfpay-new.wynk.in/wcf/payu
        callback:
          successUrl: http://localhost:8081/wynk/v1/payment/callback/{sid}
          failureUrl: http://localhost:8081/wynk/v1/payment/callback/{sid}


####### Http Client Props #######
http:
  enableTemplateRegistration: true
  templates:
    subscriptionHttpTemplate:
      pool:
        connection:
          max: 20
          maxPerHost: 500
          validateAfterInActivity: 100
          timeout: 4000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          socket:
            timeout: 6000
            factory:
              type: both
          request:
            timeout: 1000
service:
  subscription:
    api:
      root: http://subscription-statging.wynk.in

cors:
  allowed:
    origins: "*"

logging:
  path: /tmp