spring:
    profiles:
      active: ${env:dev}
    main:
      banner-mode: off
    devtools:
      add-properties: false

apb:
    callback:
      url: http://capi.wcf.internal/wynk/wynk/v1/paymentcallback/apb
    merchant:
      id: 180704
    salt: d41d8cd98f00a
    init:
      payment:
        url: https://ecom.airtelbank.com/ecom/v2/initiatePayment


debug: false
server:
  port: 8081

  ########## Management Config ##########
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,mappings,metrics,caches
    jmx:
      exposure:
        exclude: '*'
    health:
      mongo:
        enabled: false
      cassandra:
        enabled: false
      diskspace:
        enabled: false
      redis:
        enabled: false

###### log props ######
logging:
  path: /data


