###### Redis Store Props #######
session:
    redis:
      name: session-store-dev
      mode: cluster
      useSsl: false
      usePooling: true
      password: ##
      enableJmx: true
      jmxPrefix: session-store:dev
      cluster:
        nodes: 10.80.1.111:6379,10.80.0.22:6379
      connection:
        timeout: 1000
        maxTotal: 200
        minIdle: 50
        maxIdle: 100

######### MongoDB properties
app:
  mongo:
    sources:
      payment:
        nodes: 10.80.0.73,10.80.0.68:27017
        username: # None
        password: # None
        database: payments

##### mysql database props #####
spring:
  datasource:
    url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
    username: admin
    password: o7QZ?!n=eu
    hikari:
      jdbc-url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
      username: admin
      password: o7QZ?!n=eu
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 2000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 10
      maximumPoolSize: 100

  #### JPA props ######
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: false
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: UTC


####### payment props #######
payment:
  recurring:
    offset:
      day: 0
      hour: 1
  ###### lib-queue props ######
  pooling:
    queue:
      reconciliation:
        enabled: true
        name: wcf-staging-payment-reconciliation
        sqs:
          messages:
            producer:
              delayInSecond: 180
            consumer:
              delay: 20
              delayTimeUnit: SECONDS
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
      renewal:
        enabled: false
        name: wcf-staging-payment-renewal
        sqs:
          messages:
            producer:
              delayInSecond: 180
            consumer:
              delay: 20
              delayTimeUnit: SECONDS
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
      charging:
        enabled: false
        name: wcf-staging-payment-charging.fifo
        sqs:
          messages:
            producer:
              delayInSecond: 180
            consumer:
              delay: 20
              delayTimeUnit: SECONDS
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
      subscription:
        enabled: false
        name: wcf-staging-subscription
        sqs:
          messages:
            producer:
              delayInSecond: 20
            consumer:
              delay: 1
              delayTimeUnit: MINUTES
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
  ###### webview status props #######
  status:
    web:
      url: http://localhost:4200/status
  merchant:
    ####### payu props #########
    payu:
      api:
        info: https://info.payu.in/merchant/postservice.php?form=2
      internal:
        web:
          url: https://wcfpay-new.wynk.in/wcf/payu
        callback:
          successUrl: http://localhost:8081/wynk/v1/payment/callback/{sid}
          failureUrl: http://localhost:8081/wynk/v1/payment/callback/{sid}
