spring:
  profiles:
    active: ${env:local}
  main:
    banner-mode: off
  devtools:
    add-properties: false
###### SPRING AUTO-CONFIG EXCLUSION
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  jackson:
    default-property-inclusion: NON_NULL


debug: true
server:
  port: 8081

########## Management Config ##########
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,mappings,metrics,caches
    jmx:
      exposure:
        exclude: '*'
    health:
      mongo:
        enabled: false
      cassandra:
        enabled: false
      diskspace:
        enabled: false
      redis:
        enabled: false

###### log props ######
logging:
  path: /data

##### resilience props for lib-queue ######
resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

###### aws sdk props #######
amazon:
  sdk:
    regions: ap-south-1


###### Subscription Service End Point #######

service:
  subscription:
    api:
      endpoint:
        allPlans: ${service.subscription.api.root}/wynk/v1/s2s/data/allPlans

cors:
  maxAge: 3600
  allowed:
    methods: GET, PUT, PATCH, POST, OPTIONS
