spring:
    profiles:
      active: ${env:local}
    main:
      banner-mode: off
    devtools:
      add-properties: false

paytm:
    native:
      clientId: merchant-wynk
      merchantKey: RrGHVFOJyEjbp4hN
      merchantId: AirBSB68537227489657
      secret: fd13c3f9-da62-47e2-b354-8f0f18fbe90b
      website: WCF
      accounts:
        baseUrl: https://accounts.paytm.com
      services:
        baseUrl: https://securegw.paytm.in/paymentservices
      wcf:
        addMoneyUrl: https://wcfpay-new.wynk.in/paytm-native/add-money
        callbackUrl: https://capi.wynk.in/wynk/v2/s2s/subscription/callback


debug: false
server:
  port: 8081

  ########## Management Config ##########
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,mappings,metrics,caches
    jmx:
      exposure:
        exclude: '*'
    health:
      mongo:
        enabled: false
      cassandra:
        enabled: false
      diskspace:
        enabled: false
      redis:
        enabled: false

###### log props ######
logging:
  path: /data


