spring:
  application:
    name: paymentApi
  profiles:
    active: ${env}
    include: base-common,coupon-core-${env}, coupon-core-${env}, client-core-${env}, wynk-service-core-${env}
  main:
    banner-mode: off
  devtools:
    add-properties: false
  ###### SPRING AUTO-CONFIG EXCLUSION
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  jackson:
    default-property-inclusion: non_null

debug: false

server:
  port: 8081

########## Management Config ##########
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,mappings,metrics,caches
    jmx:
      exposure:
        exclude: '*'
    health:
      mongo:
        enabled: false
      cassandra:
        enabled: false
      diskspace:
        enabled: false
      redis:
        enabled: false

###### log props ######
logging:
  level:
    org.apache.catalina: off
  path: /data
  path.analytics: /logs

##### resilience props for lib-queue ######
resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

###### aws sdk props #######
amazon:
  sdk:
    regions: ap-south-1


###### Subscription Service End Point #######

service:
  subscription:
    api:
      endpoint:
        allOffers: ${service.subscription.api.root}/wynk/s2s/v1/data/allOffers
        allPartners: ${service.subscription.api.root}/wynk/s2s/v1/data/allPartners
        allPlans: ${service.subscription.api.root}/wynk/s2s/v1/data/allPlans
        allItems: ${service.subscription.api.root}/wynk/s2s/v1/data/allItems
        subscribePlan: ${service.subscription.api.root}/wynk/s2s/v1/plan/subscribe
        unSubscribePlan: ${service.subscription.api.root}/wynk/s2s/v1/plan/unsubscribe
        thanksSegmentEndpoint: ${service.subscription.api.root}/wynk/s2s/v1/user/segments
        activePlansEndpoint: ${service.subscription.api.root}/wynk/s2s/v1/user/active/plans
        trialPlanComputation: ${service.subscription.api.root}/wynk/s2s/v1/plans/trial/eligible

####### payment props #######
payment:
  payOption:
    page: ${webview.host}/#/payment-option/
  success:
    page: ${webview.host}/#/subscription/success/
  failure:
    page: ${webview.host}/#/txn-state/payment-failed/
  pending:
    page: ${webview.host}/#/txn-state/payment-pending/
  unknown:
    page: ${webview.host}/#/txn-state/payment-unknown/

cors:
  maxAge: 3600
  allowed:
    methods: GET, PUT, PATCH, POST, OPTIONS, DELETE

paytm:
  refund:
    api: ${paytm.native.services.baseUrl}/refund/apply
  validateToken:
    api: ${paytm.native.accounts.baseUrl}/user/details
  autoDebit:
    api: ${paytm.native.services.baseUrl}/order/directPay
  transactionStatus:
    api: ${paytm.native.services.baseUrl}/v3/order/status
  refundStatus:
    api: ${paytm.native.services.baseUrl}/v2/refund/status
  revokeAccessToken:
    api: ${paytm.native.accounts.baseUrl}/oauth2/token/sv1
  refreshToken:
    api: ${paytm.native.accounts.baseUrl}/oauth2/v3/token/sv1
  sendOtp:
    api: ${paytm.native.accounts.baseUrl}/v4/signin/otp/sv1/?locale=en-IN
  fetchInstrument:
    api: ${paytm.native.services.baseUrl}/paymentservices/fetch/instrument
  validateOtp:
    api: ${paytm.native.accounts.baseUrl}/v4/signin/validate/otp/sv1?locale=en-IN&anchor=enc_user_id