###### Redis Store Props #######
session:
    redis:
      name: session-store:local
      mode: standalone
      standalone:
        host: localhost
        port: 6379
        usePooling: false
        enableJmx: false
      connection:
        timeout: 1000
        maxTotal: 200
        minIdle: 50
        maxIdle: 100

###### log props ######
logging:
    path: /tmp