######  Properties #########
paytm:
  native:
    clientId: merchant-wynk-uat
    merchantKey: 2A2%#0MvWdNeg1_7
    merchantId: WYNKPr93314794046826
    secret: TR22tCjNwWIrRcPp4kDzHBNDfede3ewW
    accounts:
      baseUrl: https://accounts-uat.paytm.com
    services:
      baseUrl: https://securegw-stage.paytm.in
    wcf:
      addMoneyUrl: http://wcfpay-dev.wynk.in/paytm-native/add-money
  requesting:
    website: WEBSTAGING

apb:
  txn:
    inquiry:
      url: https://apptest.airtelbank.com/ecom/v2/inquiry
  merchant:
    id: 180704
  salt: d41d8cd98f00a
  init:
    payment:
      url: https://apptest.airtelbank.com/ecom/v2/initiatePayment

###### Redis Store Props #######
session:
  duration: 1440
  redis:
    name: session-store:local
    mode: cluster
    usePooling: true
    readTimeout: 1000
    cluster:
      nodes: wcf-redis-cluster.8hya7e.clustercfg.aps1.cache.amazonaws.com:6379
    connection:
      timeout: 1000
      maxTotal: 200
      minIdle: 50
      maxIdle: 100

##### mysql database props #####
spring:
  datasource:
    url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
    username: admin
    password: o7QZ?!n=eu
    ###### database connection pooling props ######
    hikari:
      jdbc-url: jdbc:mysql://wcf-payments-staging.cq59vpled07m.ap-south-1.rds.amazonaws.com:3306/payments
      username: admin
      password: o7QZ?!n=eu
      driver-class-name: com.mysql.cj.jdbc.Driver
      registerMbeans: true
      auto-commit: false
      connectionTimeout: 5000
      idleTimeout: 10000
      maxLifetime: 30000
      poolName: payment-datasource-pool-dev
      minimum-idle: 10
      maximumPoolSize: 100

  #### JPA props ######
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:format_sql: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: Asia/Kolkata
      hibernate.enable_lazy_load_no_trans: true
      hibernate.types.print.banner: false

#### logging props ####
logging:
  path: /tmp
  path.analytics: /tmp/logs
  level:
    in.wynk.*: INFO

####### payment props #######
payment:
  se:
    s3:
      bucket: wynk-framework-dev-ap-south-1
  encKey: BSB$PORTAL@2014#
  recurring:
    offset:
      day: 0
      hour: 1
  preDebitNotification:
    preOffsetDays: 2
    offset:
      day: 0
      hour: 1
  ###### lib-queue props ######
  pooling:
    queue:
      preDebitNotification:
        enabled: true
        name: mandate-notification-sqs-queue
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      reconciliation:
        enabled: true
        name: wcf-staging-payment-reconciliation
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      renewal:
        enabled: true
        name: wcf-staging-payment-renewal
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      charging:
        enabled: true
        name: wcf-staging-payment-charging.fifo
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      schedule:
        enabled: true
        name: wcf-staging-subscription-payment
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS
      unschedule:
        enabled: true
        name: wcf-staging-payment-recurring
        sqs:
          messages:
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
          producer:
            delayInSecond: 180
          consumer:
            delay: 20
            delayTimeUnit: SECONDS

  ###### webview status props #######
  status:
    web:
      url: http://localhost:4200/status
  merchant:
    ####### payu props #########
    payu:
      key: qFDqmx
      salt: Zbm2ZyNe
      api:
        info: https://test.payu.in/merchant/postservice.php?form=2
        payment: https://test.payu.in/_payment
    #### PhonePe props ######
    phonepe:
      id: WYNKUAT
      api:
        base:
          url: https://mercury-uat.phonepe.com
      salt: 8289e078-be0b-484d-ae60-052f117f8deb
      saltAuto: 8289e078-be0b-484d-ae60-052f117f8deb
    #### APBPaytm props ######
    apbPaytm:
      api:
        base:
          url: https://kongqa.airtel.com/preprod-84/pg-service
      auth:
        token: Basic cGF5bWVudDpwYXlAcWNrc2x2cg==
    #### Itunes props ######
    itunes:
      api:
        url: https://buy.itunes.apple.com/verifyReceipt
        alt:
          url: https://sandbox.itunes.apple.com/verifyReceipt
    #### AmazonIap props ######
    amazonIap:
      secret: 2:kjHsKYZZfkIPxwxOKaNSkZWl_6aTK1czOJANNIll40h7tyer65YZRy-Gc6MpAj3i:IS0CrRbuGNrSlRFLGkZ-jg==
      status:
        baseUrl: http://rvssandbox.wynk.in/RVSSandbox/version/1.0/verifyReceiptId/developer/

subscription:
  pooling:
    queue:
      provision:
        enabled: true
        name: wcf-staging-subscription
        sqs:
          producer:
            delayInSecond: 1

####### sms props #######
sms:
  notification:
    queue:
      name: wcf-staging-notification
      delayInSecond: 0

####### Http Client Props #######
http:
  enableTemplateRegistration: true
  templates:
    paymentGatewayHttpTemplate:
      pool:
        connection:
          max: 20
          maxPerHost: 500
          timeout: 10000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          validateAfterInActivity: 100
          socket:
            timeout: 2500
            factory:
              type: both
          request:
            timeout: 10000
    apbPaytmHttpTemplate:
      pool:
        connection:
          max: 5
          maxPerHost: 1
          timeout: 1000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          validateAfterInActivity: 100
          socket:
            timeout: 2500
            factory:
              type: both
          request:
            timeout: 5000
    paymentClientHttpTemplate:
      pool:
        connection:
          max: 5
          maxPerHost: 60
          timeout: 2000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          validateAfterInActivity: 100
          socket:
            timeout: 2500
            factory:
              type: both
          request:
            timeout: 1000
    subscriptionHttpTemplate:
      pool:
        connection:
          max: 5000
          maxPerHost: 500
          validateAfterInActivity: 100
          timeout: 4000
          defaultKeepAliveTime: 500
          closeIdleWaitTime: 500
          socket:
            timeout: 6000
            factory:
              type: both
          request:
            timeout: 1000
    externalServiceTemplate:
      pool:
        connection:
          max: 20
          maxPerHost: 20
          timeout: 1000
          defaultKeepAliveTime: 30000
          closeIdleWaitTime: 1000
          validateAfterInActivity: 100
          socket:
            timeout: 300
            factory:
              type: both
          request:
            timeout: 500

###### Service Endpoints  ######

service:
  subscription:
    api:
      root: https://subscription-staging.wynk.in
  payment:
    api:
      root: http://localhost:${server.port}

cors:
  allowed:
    origins: "*"

debug: false

webview:
  host: https://pay-stage.wynk.in

########### MONGO CONFIG ###########
wynk:
  mongodb:
    enabled: true
    sources:
      payment:
        appName: payment
        nodes: 10.80.0.128,10.80.0.240
        username: user_payments
        password: zS7VvjYRSE
        database: payments
        ########### Mongo Pool Config ###########
        connectionSettings:
          minConnectionsPerHost: 1
          maxConnectionsPerHost: 5
          threadsAllowedToBlockForConnectionMultiplier: 2
        timeOutSettings:
          serverSelectionTimeoutMs: 10000
          maxWaitTime: 1000
          connectTimeout: 1000
          socketTimeout: 2000
        readPreference: secondaryPreferred
        replicaSet: wcf
      coupons:
        appName: coupon
        nodes: 10.80.0.128,10.80.0.240
        username: user_coupons
        password: Sk6kzU8GU5
        database: coupons
        ########### Mongo Pool Config ###########
        connectionSettings:
          minConnectionsPerHost: 1
          maxConnectionsPerHost: 5
          threadsAllowedToBlockForConnectionMultiplier: 2
        timeOutSettings:
          serverSelectionTimeoutMs: 10000
          maxWaitTime: 1000
          connectTimeout: 1000
          socketTimeout: 2000
        readPreference: secondaryPreferred
        replicaSet: wcf

######## lib-auth props #######
security:
  exempt:
    paths: /wynk/v1/**,/actuator/**,/v2/api-docs,/configuration/ui,/swagger-resources/**,/configuration/security,/swagger-ui.html,/webjars/**

cache:
  caffeine:
    eviction:
      size:
        initial: 10
        maximum: 500
      time:
        expireAfterAccess: 0
        expireAfterWrite: 0
        fixed: true
        timeunit: seconds
    metrics: false
    nullable: false
  enabled: true
  mode: composite
  redis:
    cache:
      cacheNullValues: false
      keyPrefix: LOCAL
      timeunit: minutes
      ttl: 15
      usePrefix: false
    cluster:
      nodes: wcf-redis-cluster.8hya7e.clustercfg.aps1.cache.amazonaws.com:6379
    connection:
      maxIdle: 8
      maxTotal: 10
      minIdle: 5
      timeout: 2000
    enableJmx: true
    enabled: true
    jmxPrefix: local
    mode: cluster
    name: l2cache-local
    readTimeout: 1000
    usePooling: true

onelink:
  key: key_test_pgZfbR1czLvn25MY3jFKmejbACgrSztR
  url: https://api2.branch.io/v1/url

lock:
  redis:
    name: redis-lock:local
    mode: cluster
    usePooling: true
    readTimeout: 1000
    enableJmx: true
    enabled: true
    jmxPrefix: local
    cluster:
      nodes: wcf-redis-cluster.8hya7e.clustercfg.aps1.cache.amazonaws.com:6379
    connection:
      timeout: 1500
      maxTotal: 100
      minIdle: 25
      maxIdle: 50
