spring:
    profiles:
      active: ${env:local}
    main:
      banner-mode: off
    devtools:
      add-properties: false

debug: false
server:
  port: 8081

  ########## Management Config ##########
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,mappings,metrics,caches
    jmx:
      exposure:
        exclude: '*'
    health:
      mongo:
        enabled: false
      cassandra:
        enabled: false
      diskspace:
        enabled: false
      redis:
        enabled: false

###### log props ######
logging:
  path: /data

payment:
  pooling:
    queue:
      reconciliation:
        enabled: true
        name: wcf-staging-payment-reconciliation
        delay: 20
        delayTimeUnit: SECONDS
        sqs:
          messages:
            producer:
              delayInSecond: 20
            extractor:
              batchSize: 5
              waitTimeInSeconds: 10
      renewal:
        enabled: false
        name: wcf-staging-payment-renewal
        delay: 1
        delayTimeUnit: MINUTES
      charging:
        enabled: false
        name: wcf-staging-payment-charging.fifo
        delay: 1
        delayTimeUnit: MINUTES
      subscription:
        enabled: false
        name: wcf-staging-subscription
        delay: 1
        delayTimeUnit: MINUTES
  merchant:
    encKey: BSB$PORTAL@2014#
####### payu props #########
    payu:
      key: aU2Uoi
      salt: 6vbnfVtw


resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

amazon:
  sdk:
    regions: ap-south-1
