spring:
  application:
    name: paymentApi
  profiles:
    active: ${env}
    include: base-common, coupon-core-${env}, client-core-${env},vas-client-${env}, wynk-service-core-${env}, error-codes-core-${env}, scheduler-core-${env}, country-currency-core-${env}, tinylytics-${env}
  main:
    banner-mode: off
  devtools:
    add-properties: false
  ###### SPRING AUTO-CONFIG EXCLUSION
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  jackson:
    default-property-inclusion: non_null
  scheduler:
    jobStore:
      keyPrefix: 'payment:${env}:'

debug: false

server:
  port: 8081

########## Management Config ##########
management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health,mappings,metrics,caches
    jmx:
      exposure:
        exclude: '*'
  health:
    mongo:
      enabled: false
    cassandra:
      enabled: false
    diskspace:
      enabled: false
    redis:
      enabled: false

###### log props ######
logging:
  appName: payment
  profile: ${env}
  level:
    org.apache.catalina: off
    org.quartz: DEBUG
    in.wynk.scheduler.core: DEBUG
  path: /data
  path.analytics: /logs

##### resilience props for lib-queue ######
resilience:
  retryProperties:
    maxAttempts: 3
    waitDuration: 10000

###### aws sdk props #######
amazon:
  sdk:
    regions: ap-south-1


###### Subscription Service End Point #######

service:
  subscription:
    api:
      endpoint:
        allPlans: ${service.subscription.api.root}/wynk/s2s/v1/data/allPlans
        allProducts: ${service.subscription.api.root}/wynk/s2s/v1/data/allProducts
        allOffers: ${service.subscription.api.root}/wynk/s2s/v1/data/allOffers
        allPartners: ${service.subscription.api.root}/wynk/s2s/v1/data/allPartners
        allItems: ${service.subscription.api.root}/wynk/s2s/v1/data/allItems
        subscribePlan: ${service.subscription.api.root}/wynk/s2s/v1/plan/subscribe

        unSubscribePlan: ${service.subscription.api.root}/wynk/s2s/v1/plan/unsubscribe
        thanksSegmentEndpoint: ${service.subscription.api.root}/wynk/s2s/v1/user/segments
        activePlansEndpoint: ${service.subscription.api.root}/wynk/s2s/v1/user/active/plans
        renewalPlanEligibility: ${service.subscription.api.root}/wynk/s2s/v1/renewal/plan/eligibility
        selectivePlanComputation: ${service.subscription.api.root}/wynk/s2s/v1/plans/selective/eligible
        selectivePlanComputationV2: ${service.subscription.api.root}/wynk/s2s/v2/plans/selective/eligible


  ####### payment props #######
  payment:
    api:
      endpoint:
        winBack: ${service.payment.api.root}/wynk/s2s/v1/customer/winback/

####### payment props #######session-out
payment:
  callback:
    web: ${service.payment.api.root}/wynk/v1/payment/callback
    s2s: ${service.payment.api.root}/wynk/v1/callback
  rajtv:
    payOption:
      page: ${webview.rajtv.host}/#/payment-option/
    success:
      page: ${webview.rajtv.host}/#/subscription/success/
    failure:
      page: ${webview.rajtv.host}/#/txn-state/payment-failed/
    pending:
      page: ${webview.rajtv.host}/#/txn-state/payment-pending/
    unknown:
      page: ${webview.rajtv.host}/#/txn-state/payment-unknown/
    timeout:
      page: ${webview.rajtv.host}/#/txn-state/session-out/
  iqvideo:
    payOption:
      page: ${webview.iqvideo.host}/#/payment-option/
    success:
      page: ${webview.iqvideo.host}/#/subscription/success/
    failure:
      page: ${webview.iqvideo.host}/#/txn-state/payment-failed/
    pending:
      page: ${webview.iqvideo.host}/#/txn-state/payment-pending/
    unknown:
      page: ${webview.iqvideo.host}/#/txn-state/payment-unknown/
    timeout:
      page: ${webview.iqvideo.host}/#/txn-state/session-out/
  enterr10:
    payOption:
      page: ${webview.enterr10.host}/#/payment-option/
    success:
      page: ${webview.enterr10.host}/#/subscription/success/
    failure:
      page: ${webview.enterr10.host}/#/txn-state/payment-failed/
    pending:
      page: ${webview.enterr10.host}/#/txn-state/payment-pending/
    unknown:
      page: ${webview.enterr10.host}/#/txn-state/payment-unknown/
    timeout:
      page: ${webview.enterr10.host}/#/txn-state/session-out/
  payOption:
    page: ${webview.host}/#/payment-option/
  success:
    page: ${webview.host}/#/subscription/success/
  failure:
    page: ${webview.host}/#/txn-state/payment-failed/
  pending:
    page: ${webview.host}/#/txn-state/payment-pending/
  unknown:
    page: ${webview.host}/#/txn-state/payment-unknown/
  timeout:
    page: ${webview.host}/#/txn-state/session-out/
  polling:
    page: ${webview.host}/#/txn-state/payment-poll/
  googlePlay:
      baseUrl: https://androidpublisher.googleapis.com/androidpublisher/v3/applications/
      purchaseUrl: /purchases/subscriptionsv2/
      key: AIzaSyBr3yWKW5kso1e8H1_JmDFff1CK0b787oc
      authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
      tokenUrl: https://oauth2.googleapis.com/token
      rajTv:
        privateKey: -----BEGIN PRIVATE KEY-----MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCXzhHvSY+RO33Ggdklxie/hw/hGpB5Z42mYjCsxzwdXTQd/aVUGA+JD/ldZHWdaRcEayKYn86bIlF/HHIaXsFhfXDXcsFLfgCGjZ8Yo54ssMjj/rYw/5SDs7P9XfMhJymIDNTuC/LLmzq0I6WwgFXatWxek+I5DSAaDbx2rpvTdie8dY3uM8zkNQBtqKhM6Y76EWgFtJPLNT18CMiXJGYUucZB59P5mJAjDem0AVk6RRb8myqWX9OCVr92Nxct2k8OaXRH2p7LTEpbx4K9wzAYAtewooxzQ+H9sx/ZXfaw3RQu26b8dflLreXnL4BpMpnIDy17v9lh54UM8A5E4RtRAgMBAAECggEAHn36BEKWX+m/PdxfLcM7wLD0c5bOZlRyk3UtqcbrQEq0aUHFr7qVhEZ9JFFFfrTZNr3+WQHgkjC2hf3EvZ9C4L49qEkYon1QxbY0utJCt19bOtCy7+ymfD3gbYgtif8/zGAndRlZT6SCiiSO54EfvaqrdePmkOceB52yuXQhQLwv1MA/XH9x5NmiN3SlKZoNOHLbhG1Jj2bA0HYuGlMnlc44QKin+RdQ4aG7OXhuC8+hddHT3qfvT3TtsD1hTk3MpoS8BlpZSP6thwfcc6AIaoGVrpQP8aR3GmKZFpP38RLPbhhUzCsw9zKtigtJMYvh+K0PKojc71NvXG+iaWr/8QKBgQDGN4nh18uf3E0XiGM/uCzy92SmJYS9ftpEG26S813ajh4NjoNE0f8O58lNbhiBC5QMRBwCYzqkmcSQe9XbozDSCJfH6XDCbBBcz0Prn0ZB9bAxDmKaJPyFHiuTwuptCoHgXncQtdUJpqeUJbbwuYzfMb2CGagper0FV+iC72hQcwKBgQDEDuoxKwtAKTVTrV0fLu17rgpCUUZbYUYzWDiJLJR9gVyEhuFlgRHN6XZM3f3bSgpRUutnqlHzaZ3UVRk/q6laZqNXDZ+eixtw+ir//Lf4bjR3LhQaVVl5DgN5PXr00kC+pdj6sLtIvjwiXm5O32NimSNjg9oW4/gyE8tvxsgIKwKBgFI8fJIca7i5N6rJxROMn+l1xmZALqBH3tpe3zNMkOW6DLHnLIMC9OUEOTpMsRHo8dVc9Jnw/UWJHkordoCXZgvd0Mr6CPRAzVEUFMPO4uE+w4i2xSXaroG0ELRPK99tepDR4GgoaGiGogQO2aVp9g4rnso5RtFewMlUvXyFQywNAoGAEp3T8Q1ESThgfuyUThS3qinRgZCUHLM05kU3QRdBllVFQrRIDMpftWy4tf3SUBNMvYIhJjvPAk0CFppqBli3gQUD940snfJZjbXDhYEquuVECBkRAZsfHtaMz+NdnIembDP1UYCcmACwVxceZFDj8AXYjWeEuu20sJSemaOHdPcCgYAa1OzUuNb8VVaHUJUp4/0o4wc0YBp7AoQ8z8TJhp8aniz8oBXw3GCJmGavtEUWwRPTG29iQ8DfwtD/+bHGOFHgfMsb0ItYOWMz4Y4V21o+uIe5rCtMfxQkUoCpXmppaMlyhwQearPvg+aNXyiInxf6hstiiiFC/RxJ9GU1ZARCsw==-----END PRIVATE KEY-----
        privateKeyId: c2d5cb3fb12f09a082505b2a79f92db0061f866f
        clientEmail: raj-tv-service@raj-tv-363111.iam.gserviceaccount.com
cors:
  maxAge: 3600
  allowed:
    methods: GET, PUT, PATCH, POST, OPTIONS, DELETE

paytm:
  refund:
    api: ${paytm.native.services.baseUrl}/refund/apply
  validateToken:
    api: ${paytm.native.accounts.baseUrl}/user/details
  autoDebit:
    api: ${paytm.native.services.baseUrl}/order/directPay
  transactionStatus:
    api: ${paytm.native.services.baseUrl}/v3/order/status
  refundStatus:
    api: ${paytm.native.services.baseUrl}/v2/refund/status
  revokeAccessToken:
    api: ${paytm.native.accounts.baseUrl}/oauth2/token/sv1
  refreshToken:
    api: ${paytm.native.accounts.baseUrl}/oauth2/v3/token/sv1
  sendOtp:
    api: ${paytm.native.accounts.baseUrl}/v4/signin/otp/sv1/?locale=en-IN
  fetchInstrument:
    api: ${paytm.native.services.baseUrl}/paymentservices/fetch/instrument
  validateOtp:
    api: ${paytm.native.accounts.baseUrl}/v4/signin/validate/otp/sv1?locale=en-IN&anchor=enc_user_id

apbpaytm:
  refund:
    api: ${apbpaytm.native.services.baseUrl}/refund/apply
  validateToken:
    api: ${apbpaytm.native.accounts.baseUrl}/user/details
  autoDebit:
    api: ${apbpaytm.native.services.baseUrl}/order/directPay
  transactionStatus:
    api: ${apbpaytm.native.services.baseUrl}/v3/order/status
  refundStatus:
    api: ${apbpaytm.native.services.baseUrl}/v2/refund/status
  revokeAccessToken:
    api: ${apbpaytm.native.accounts.baseUrl}/oauth2/token/sv1
  refreshToken:
    api: ${apbpaytm.native.accounts.baseUrl}/oauth2/v3/token/sv1
  sendOtp:
    api: ${apbpaytm.native.accounts.baseUrl}/v4/signin/otp/sv1/?locale=en-IN
  fetchInstrument:
    api: ${apbpaytm.native.services.baseUrl}/paymentservices/fetch/instrument
  validateOtp:
    api: ${apbpaytm.native.accounts.baseUrl}/v4/signin/validate/otp/sv1?locale=en-IN&anchor=enc_user_id

aps:
  payment:
    encryption:
      key:
        path: ${payment.merchant.aps.encryption.key}
    init:
      settlement:
        api: ${payment.merchant.aps.api.base}/pg-service/v1/payment/hive-split-payment
      charge:
        api: ${payment.merchant.aps.api.base}/pg-service/v1/payment/initiate
        upi:
          api: ${payment.merchant.aps.api.base}/pg-service/v1/payment/initiate/upi
      refund:
        api: ${payment.merchant.aps.api.base}/pg-service/v1/payment/refund
    verify:
      bin:
        api: ${payment.merchant.aps.api.base}/ps/payment-options/v2/card-details
      vpa:
        api: ${payment.merchant.aps.api.base}/pg-service/v1/validate/vpa/{vpa}
    option:
      api: ${payment.merchant.aps.api.base}/ps/payment-options/v3/fetch
    saved:
      option:
        api: ${payment.merchant.aps.api.base}/ps/payment-options/saved-options
      details:
        api:
    refund:
      status:
        api: ${payment.merchant.aps.api.base}/pg-service/v1/payment/refund/enquiry
    charge:
      status:
        api: ${payment.merchant.aps.api.base}/pg-service/v1/payment/status/order/{txnId}?fetchHistoryTransaction={fetchHistoryTransaction}

branch:
  onelink:
    key: ${onelink.key}
    url: ${onelink.url}